### ISSUE TITLE
k8s/读懂deployment的定义

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#11]
上节参照了官方文档操作了一下nginx的部署，但很多地方填写的是缺省值，这样不利于全面地掌握deployment的相关知识，今天将按照下面节点展开实践：
1. dashboard的deployment定义
2. deployment定义

# dashboard的deployment定义
```
kind: Deployment                            # 类型
apiVersion: apps/v1beta2                    # yaml格式版本
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:                                       # 规格说明
  replicas: 1                               # 副本个数，Controller Manager会保持这个数量的副本，0为删除
  revisionHistoryLimit: 10                  # 表示历史版本保留的个数，用于回滚
  selector:                                 # 选择器
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:                                 # Pod，至少要有一个Label
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:                                   # 容器规格说明，定义容器的属性
      containers:
      - name: kubernetes-dashboard          # 容器名字，必填
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.1   # 镜像，必填
        ports:                              # 容器暴露端口定义
        - containerPort: 8443               # 容器端口
          protocol: TCP                     # 端口协议，支持TCP、UDP，默认是TCP
        args:                               # 容器启动的命令参数列表
          - --auto-generate-certificates
        volumeMounts:                       # 挂载到容器内部的存储卷配置
        - name: kubernetes-dashboard-certs
          mountPath: /certs
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:                      # object，用于探测容器健康状态，超过失败次数会重启容器，有exec、httpGet、tcpSocket等模式
          httpGet:                          # 对Pod内各个容器进行健康检测
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 30           # 容器启动后进行首次探测的时间，单位s
          timeoutSeconds: 30                # 超时时间30
      volumes:                              # 该Pod上定义的共享存储卷列表
      - name: kubernetes-dashboard-certs    # 共享存储卷名称
        secret:                             # 存储卷类型，有secret、emptyDir、hostPath、configMap、aws云等
          secretName: kubernetes-dashboard-certs
      - name: tmp-volume
        emptyDir: {}                        # 临时目录，Pod销毁时删除
      serviceAccountName: kubernetes-dashboard      # 绑定ServiceAccount账号来操作
      tolerations:                                  # 部署策略，下面是不允许在Master上部署dashboard
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

# Deployment定义
在了解基本概念以及解析了dashboard的yaml定义后，我们来看看一个Deployment的完整定义。
```yaml
kind: Deployment                            # Require，类型
apiVersion: apps/v1beta2                    # Require，yaml格式版本
metadata:                                   # Require，元数据
  labels:                                   # 标签列表
    your-key: string
  annotation:                               # 注解，可以用于限制带宽、请求速率等
    your-annotation: string                 
  name: string                              # Require，Pod名称
  namespace: string                         # Require，命名空间，默认default
spec:                                       # Require，Pod中容器的详细说明
  replicas: number                          # Require，副本个数，0为删除
  revisionHistoryLimit: number              # 表示历史版本保留的个数，用于回滚，默认10
  selector:                                 # Require，选择器
    matchLabels:                            # Require，至少选择一个Label
      your-key: string                      # 标签，需要与下面的保持一直
  template:                                 # 最核心的部分，Pod的定义，至少要有一个Label
    metadata:                               # Require，Pod元数据
      labels:
        your-key: string
    spec:                                   # Require，容器规格说明，定义容器的属性
      containers:
      - name: string                        # Require，容器名字，必填
        image: string                       # Require，镜像
        imagePullPolicy: string             # 镜像拉去策略，可选Always、Never、IfNotPresent，默认Always
        ports:                              # 容器暴露端口定义
        - hostPort: string                  # 容器所在主机的端口号，通常不设置
          containerPort: number             # 容器端口
          protocol: TCP                     # 端口协议，支持TCP、UDP，默认是TCP
          name: string                      # 端口名称
        command:                            # 启动命令，若是没指定，则使用镜像打包时的启动命令
          - string
        args:                               # 容器启动的命令参数列表
          - string
        workingDir: string                  # 容器工作目录
        env:                                # 容器环境变量
        - name: string
          value: string
        resources:                          # 资源限制
          limits:
          - cpu: string                     # 最大可用CPU，单位为内核数，同docker参数--cpu-shares
            memory: string                  # 最大可用内存，单位MiB、GiB，同docker参数--memory
          requests:
          - cpu: string                     # 启动可用CPU内核数，同docker参数--cpu-shares
            memory: string                  # 启动可用内存，单位MiB、GiB，同docker参数--memory
        volumeMounts:                       # 挂载到容器内部的存储卷配置
        - name: string                      # 卷名称
          mountPath: string                 # 卷在容器内Mount的绝对路径，不多于512字符
          readOnly: boolean                 # 是否只读模式，默认是false
        livenessProbe: object               # 健康检测，见livenessProbe
          initialDelaySeconds: 30           # 容器启动后进行首次探测的时间，单位s
          timeoutSeconds: 30                # 超时时间30s
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          type: object                      # 健康检查探针，见livenessProbe
      volumes:                              # 该Pod上定义的共享存储卷列表
      - name: string                        # 共享存储卷名称
        type: object                        # 存储卷类型，Volumes节点
      serviceAccountName: string            # 绑定ServiceAccount账号来操作
      restartPolicy:                        # 重启策略，可选值有Always、OnFailure，默认Always
      dnsPolicy: ClusterFirst               # dns解析
      restartPolicy: Always                 # 重启策略
      securityContext: {}                   # 
      tolerations:                          # 部署策略
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

> 推荐使用Deployment来部署Pod，不建议直接使用Pod

deployment用得最多，需要反复操作直到熟练掌握，接下来将会在此节的基础上展开各个知识点的实践。
