### ISSUE TITLE
k8s/如何使用Secret管理机密信息

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#12]
应用启动过程中可能需要一些敏感信息，比如访问数据库的用户名密码或者秘钥。将这些信息直接保存在容器镜像中显然不妥，Kubernetes 提供的解决方案是 Secret。

Secret 会以密文的方式存储数据，避免了直接在配置文件中保存敏感信息。Secret 会以 Volume 的形式被 mount 到 Pod，容器可通过文件的方式使用 Secret 中的敏感数据；此外，容器也可以环境变量的方式使用这些数据。

假设我们想Secret包含以下信息，可以通过以下几种方式创建：
username: admin
password: 1f2d1e2e67df

**1、手动使用Yaml文件创建**
首先，创建Secret。
```yaml
[root@k8s-node1 svr]# cat << EOF > secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: test-secret
  name: test-secret
type: Opaque
data:
  username: `echo -n "admin" | base64`
  password: `echo -n "1f2d1e2e67df" | base64`
EOF
```
> 这里偷了个懒，直接将yaml的定义与账密编码合一起了，正常的要分开处理。

接着，我们创建secret，并查看
```bash
[root@k8s-node1 svr]# kubectl create -f secret.yaml 
secret "test-secret" created
[root@k8s-node1 svr]# kubectl describe secret test-secret 
Name:         test-secret
Namespace:    default
Labels:       app=test-secret
Annotations:  <none>

Type:  Opaque

Data
====
password:  12 bytes
username:  5 bytes
```
发现Secret`test-secret`已经创建成功。

**2、使用--from-file创建**
```
[root@k8s-node1 svr]# echo -n "admin" > ./username
[root@k8s-node1 svr]# echo -n "1f2d1e2e67df" > ./password
[root@k8s-node1 svr]# kubectl create secret generic mysecret --from-file=./username --from-file=./password
secret "mysecret" created
```

**3、使用--from-literal创建**
```
[root@k8s-node1 svr]#  kubectl create secret generic mysecret2 --from-literal=username=admin--from-literal=password=1f2d1e2e67df
secret "mysecret2" created
```

**4、使用--from-en-file创建**
首先，创建配置文件，有点类似于conf文件，每行使用k=v对应一项信息。
```bash
[root@k8s-node1 svr]#  cat << EOF > secret-env.txt
username=admin
password=1f2d1e2e67df
EOF

[root@k8s-node1 svr]#  kubectl create secret generic mysecret3 --from-env-file=secret-env.txt
secret "mysecret3" created
```
Secret已经创建完毕，后续将会在Volume中使用，这里暂不展开。
## 参考
[Secrets](https://kubernetes.io/docs/concepts/configuration/secret/)
