### ISSUE TITLE
k8s/如何使用存储卷Volume

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#14]
我们经常会说：容器和 Pod 是短暂的，其含义是它们的生命周期可能很短，会被频繁地销毁和创建。容器销毁时，保存在容器内部文件系统中的数据都会被清除。

为了持久化保存容器的数据，可以使用 Volume。

本质上，Volume 是一个目录，这一点与 Docker Volume 类似。当 Volume 被 mount 到 Pod，Pod 中的所有容器都可以访问这个 Volume。同时Volume 也支持多种 backend 类型，包括 emptyDir、hostPath、GCE Persistent Disk、AWS Elastic Block Store、NFS、Ceph 等，下面我们挑几个常用的展开说明。
## **emptyDir**
临时目录，生命周期跟Pod相同，我们通过下面例子来详细解析：
```yaml
[root@k8s-node1 svr] cat << EOF > volume-empty-dir.yaml
apiVersion: v1
kind: Pod
metadata:
  name: producer-consumer
spec:
  containers:
  - image: busybox
    name: producer
    volumeMounts:
    - mountPath: /producer_dir                                      # 容器将`shared-volume`挂载到目录`/producer_dir`
      name: shared-volume
    args:
    - /bin/sh
    - -c
    - echo "this is is a message" > /producer_dir/hello; sleep 30000;
  - image: busybox
    name: consumer
    volumeMounts:                                                            
    - mountPath: /consumer_dir                                      # 容器将`shared-volume`挂载到目录`/consumer_dir`
      name: shared-volume
    args:
    - /bin/sh
    - -c
    - cat /consumer_dir/hello; sleep 30000;
  volumes:                                                          # volume 定义
  - name: shared-volume
    emptyDir: {}
EOF
```
使用`kubectl logs`查看Pod日志
```bash
[root@k8s-node1 svr]# kubectl get pod producer-consumer -o wide
NAME                READY     STATUS    RESTARTS   AGE       IP              NODE
producer-consumer   2/2       Running   0          40s       10.233.76.243   k8s-node3
[root@k8s-node1 svr]# kubectl logs producer-consumer consumer 
this is is a message
```

> emptyDir 是 Host 上创建的临时目录，其优点是能够方便地为 Pod 中的容器提供共享存储，不需要额外的配置。但它不具备持久性，如果 Pod 不存在了，emptyDir 也就没有了。根据这个特性，emptyDir 特别适合 Pod 中的容器需要临时共享存储空间的场景。

## **hostPath**
相对于empty Volume，Pod所在宿主机目录，即使Pod被销毁，但其数据依旧存在Node上，我们来看看scheduler-manage的定义：
```yaml
[root@k8s-node1 svr]# kubectl get --namespace=kube-system pod kube-scheduler-k8s-node1 -o yaml
apiVersion: v1
kind: Pod
......
    volumeMounts:
    - mountPath: /etc/ssl
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/pki/tls
      name: etc-pki-tls
      readOnly: true
    - mountPath: /etc/pki/ca-trust
      name: etc-pki-ca-trust
      readOnly: true
    - mountPath: /etc/kubernetes/ssl
      name: etc-kube-ssl
      readOnly: true
    - mountPath: /etc/kubernetes/kube-scheduler-kubeconfig.yaml
      name: kubeconfig
      readOnly: true
.....
  volumes:
  - hostPath:
      path: /etc/ssl
      type: ""
    name: ssl-certs-host
  - hostPath:
      path: /etc/pki/tls
      type: ""
    name: etc-pki-tls
  - hostPath:
      path: /etc/pki/ca-trust
      type: ""
    name: etc-pki-ca-trust
  - hostPath:
      path: /etc/kubernetes/ssl
      type: ""
    name: etc-kube-ssl
  - hostPath:
      path: /etc/kubernetes/kube-scheduler-kubeconfig.yaml
      type: ""
    name: kubeconfig
......
```
我们发现，scheduler-manager定义了5个hostPath Volume，`ssl-certs-host`、`etc-pki-tls`、`etc-pki-ca-trust`、`etc-kube-ssl`、`kubeconfig`。
如果Pod被销毁，hostPath对应的目录依旧被保留。从这点看来，hostPath的持久性比emptyDir稍微强了一点，不过 Pod会与Node耦合，在集群调度下会发生位移，大部分情况下都不会使用到hostPath Volume。
> 此处由于pod的规格说明过多，此处只挑了卷部分做说明
## **secret**
挂载集群预定义的secret对象到容器内部，其格式如下：
```yaml
[root@k8s-node1 svr] cat << EOF > volume-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: volume-secret
  name: volume-secret
type: Opaque
data:
  username: `echo -n "admin" | base64`
  password: `echo -n "1f2d1e2e67df" | base64`
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-secret
spec:
  containers:
  - image: busybox
    name: volume-secret
    args:
    - /bin/sh
    - -c
    - sleep 10; touch /tmp/healthy; sleep 30000;
    volumeMounts:
    - name: volume-secret
      mountPath: "/etc/volume-secret"
      readOnly: true
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: volume-secret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: volume-secret
          key: password
  volumes:
  - name: volume-secret
    secret:
      secretName: volume-secret
      defaultMode: 256                                                # 默认400
#      items:                                                         # ①
#      - key: username
#        path: relative/username
#        mode: 511
#      - key: password
#        path: relative/password
#        mode: 511
EOF
```
执行并查看Secret是否读取成功
```
[root@k8s-node1 svr]#kubectl apply -f volume-secret.yaml 
secret "volume-secret" created
pod "volume-secret" created
[root@k8s-node1 svr]# kubectl exec -it volume-secret sh
/ # ls /etc/volume-secret/
password  username
/ # cat /etc/volume-secret/password 
1f2d1e2e67df
/ # cat /etc/volume-secret/username 
admin
/ # echo $SECRET_USERNAME
admin
/ # echo $SECRET_PASSWORD
1f2d1e2e67df
```
①、使用item可以单独读取变量并存储到容器的相对路径里面去，比如上面的`/etc/volume-secret/relative/`

> 需要注意的是，环境变量读取 Secret 很方便，但无法支撑 Secret 动态更新。

## **configMap**
ConfigMap其使用跟Secret类似，
```yaml
[root@k8s-node1 svr] cat << EOF > volume-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: volume-configmap
  name: volume-configmap
data:
  url: http://www.baidu.com
  path: /aaa
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-configmap
spec:
  containers:
  - image: busybox
    name: volume-configmap
    args:
    - /bin/sh
    - -c
    - sleep 10; touch /tmp/healthy; sleep 30000;
    volumeMounts:
    - name: volume-configmap
      mountPath: "/etc/volume-configmap"
      readOnly: true
    env:
    - name: CONFIG_URL
      valueFrom:
        configMapKeyRef:
          name: volume-configmap
          key: url
    - name: CONFIG_PATH
      valueFrom:
        configMapKeyRef:
          name: volume-configmap
          key: path
  volumes:
  - name: volume-configmap
    configMap:
      name: volume-configmap
      defaultMode: 256                                                # 默认400
#      items:                                                         # ①
#      - key: url
#        path: url
#        mode: 511
#      - key: path
#        path: path
#        mode: 511
EOF
```
执行并查看ConfigMap是否正常读取
```
[root@k8s-node1 svr]# kubectl exec -it volume-configmap sh
/ # echo $CONFIG_URL
http://www.baidu.com
/ # echo $CONFIG_PATH
/aaa
/ # ls /etc/volume-configmap/
path  url
/ # 
```
值得注意的是，
1、通常都是会挂载文件，而不是kv对。
2、ENV 是在容器启动的时候注入的，启动之后 kubernetes 就不会再改变环境变量的值，且同一个 namespace 中的 pod 的环境变量是不断累加的，参考 Kubernetes中的服务发现与docker容器间的环境变量传递源码探究。为了更新容器中使用 ConfigMap 挂载的配置，可以通过滚动更新 pod 的方式来强制重新挂载 ConfigMap，也可以在更新了 ConfigMap 后，先将副本数设置为 0，然后再扩容。

## **其他**
除了以上共享存储卷之外，目前还支持
- GCEPersistentDisk 
- AWSElasticBlockStore 
- AzureFile 
- AzureDisk 
- FC (Fibre Channel) 
- FlexVolume 
- Flocker 
- NFS 
- iSCSI 
- RBD (Ceph Block Device) 
- CephFS 
- Cinder (OpenStack block storage) 
- Glusterfs 
- VsphereVolume 
- Quobyte Volumes 
- VMware Photon 
- Portworx Volumes 
- ScaleIO Volumes 

通常除了常用的Secret、ConfigMap等本地Volume，生产环境还使用的是云服务商提供的云存储。接下来我们将使用分布式文件存储系统Ceph来实践。
