### ISSUE TITLE
k8s/如何使用StorageClasses

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#17]
前面我们使用了nfs作为k8s的存储后端，但实际上nfs的支持度是不够的，比如不支持扩容、不支持`Delete`策略等。业界也不推荐使用其作为k8s的存储后端，今天我们将nfs替换成ceph，展开步骤如下，
1、创建secret
2、运行StorageClass
3、动态扩容PVC

# 1、创建secret

## 1.1 获取ceph密钥
```
[root@k8s-node1 ceph]# ceph auth get client.admin 2>&1 |grep "key = " |awk '{print  $3'} > /tmp/ceph.secret 
[root@k8s-node1 ceph]# cat /tmp/ceph.secret 
AQAQB6Ra3ddHLxAAoBJ3///lxgVxUPwJ1Dxdxw==
```
## 1.2 创建k8s secret
```
[root@k8s-node1 ceph]# kubectl create secret generic ceph-admin-secret --from-file=/tmp/ceph.secret --namespace=kube-system 
secret "ceph-admin-secret" created
```
> 需要注意，secret跟namespace绑定

# 2、运行StorageClass
## 2.1 定义StorageClass
```
[root@k8s-node1 ceph]# cat << EOF > storageclass-ceph.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.56.101:6789,192.168.56.102:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  pool: kube
  userId: admin
  userSecretName: ceph-admin-secret
  imageFormat: "2"
  imageFeatures: "layering"
EOF
```
> admin、user是ceph的两种用户，默认创建了admin，这里偷个懒都用默认的，需要使用多账户请创建不同用户

## 2.2 运行并查看
```
[root@k8s-node1 ceph]# kubectl create -f storageclass-ceph.yml 
storageclass "rbd" created
[root@k8s-node1 ceph]# kubectl get storageclass 
NAME      PROVISIONER         AGE
rbd      kubernetes.io/rbd   12s
```

## 2.3 测试
```
[root@k8s-node1 ceph]# cat << EOF > storageclass-ceph-testing.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-pvc-test
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: rbd
EOF
```
我们来查看一下PVC是否创建成功
```
[root@k8s-node1 ceph]# kubectl describe pvc ceph-pvc-test
Name:          ceph-pvc-test
Namespace:     default
StorageClass:  rbd
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type     Reason              Age               From                         Message
  ----     ------              ----              ----                         -------
  Warning  ProvisioningFailed  6s (x2 over 19s)  persistentvolume-controller  Failed to provision volume with StorageClass "fast": failed to get admin secret from ["kube-system"/"ceph-admin-secret"]: failed to get secret from ["kube-system"/"ceph-admin-secret"]
```
很遗憾，PVC创建失败，发现无法读取secret，一番搜索后发现，发现了[官方说明](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd/deploy)，原来我们的k8s集群时开启了rbac认证的，而ClusterRoleBinding等默认绑定 namespace: default，没权限。
```
[root@k8s-node1 ceph]# cat << EOF > ceph-rdbc.yml
# creaet serviceaccount
apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: rbd-provisioner  
  namespace: kube-system  
---
# create clusterrole
kind: ClusterRole  
apiVersion: rbac.authorization.k8s.io/v1beta1  
metadata:  
  name: rbd-provisioner  
  namespace: kube-system  
rules:  
  - apiGroups: [""]  
    resources: ["persistentvolumes"]  
    verbs: ["get", "list", "watch", "create", "delete"]  
  - apiGroups: [""]  
    resources: ["persistentvolumeclaims"]  
    verbs: ["get", "list", "watch", "update"]  
  - apiGroups: ["storage.k8s.io"]  
    resources: ["storageclasses"]  
    verbs: ["get", "list", "watch"]  
  - apiGroups: [""]  
    resources: ["events"]  
    verbs: ["list", "watch", "create", "update", "patch"]  
  - apiGroups: [""]  
    resources: ["secrets"]  
    verbs: ["get"]
---
# clusterrole binding
kind: ClusterRoleBinding  
apiVersion: rbac.authorization.k8s.io/v1beta1  
metadata:  
  name: rbd-provisioner  
  namespace: kube-system  
subjects:  
  - kind: ServiceAccount  
    name: rbd-provisioner  
    namespace: kube-system  
roleRef:  
  kind: ClusterRole  
  name: rbd-provisioner  
  apiGroup: rbac.authorization.k8s.io
---
# create deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbd-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
    spec:
      containers:
      - name: rbd-provisioner
        image: "quay.io/external_storage/rbd-provisioner:v0.1.0"
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd
      serviceAccount: rbd-provisioner
EOF
```

> 注意，镜像源quay.io很慢，请自备梯子或者自行拉去，否则会一直卡住

修改上面storageClass的定义
```
[root@k8s-node1 ceph]# cat << EOF > storageclass-ceph.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.56.101:6789,192.168.56.102:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: kube-system
  pool: kube
  userId: admin
  userSecretName: ceph-admin-secret
  imageFormat: "2"
  imageFeatures: "layering"
EOF
```
> 将provisioner制定为我们自己实现的`ceph.com/rbd`

删除SC、PVC，再重新绑定
```
[root@k8s-node1 ceph]# kubectl delete -f storageclass-ceph.yml -f storageclass-ceph-testing.yml 
storageclass "rbd" deleted
persistentvolumeclaim "ceph-pvc-test" deleted
[root@k8s-node1 ceph]# kubectl create -f storageclass-ceph.yml -f storageclass-ceph-testing.yml 
storageclass "rbd" created
persistentvolumeclaim "ceph-pvc-test" created
```
查看PVC
```
[root@k8s-node1 ceph]# kubectl get pvc -n kube-system 
NAME            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
ceph-pvc-test   Bound     pvc-12ee9c45-2604-11e8-8373-08002760691e   1Gi        RWO            rbd            12s
nfs-pvc1        Bound     nfs-pv1                                    128Mi      RWO            nfs            5d
```
至此，k8s已成功使用ceph集群，放心地使用了。
> 我们也可以看到，使用storageClass的灵活性就在这里，不用每次都创建PV，管理员可以自定义多种后端文件存储系统，而这些对于Pod开发人员无感知，很好地起到隔离作用。

那么，突然有一天，我们发现定义好的PVC空间不够了，怎么办？能扩展吗？答案是肯定的，接下来我们看看PVC的容量扩容。

# 3、PVC扩容
目前，k8s集群目前支持以下PVC的扩容：
- gcePersistentDisk
- awsElasticBlockStore
- Cinder
- glusterfs
- rbd

但需要注意的是api-server配置了准入控制(`admisson-control`)`PersistentVolumeClaimResize`，并且StorageClass设置了`allowVolumeExpansion: true`，这个值默认是`false`。

## 参考
[StorageClasses](https://kubernetes.io/docs/concepts/storage/storage-classes/)
