### ISSUE TITLE
k8s/k8s基本概念以及架构设计

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#2]
Kubernetes（k8s）是Google开源的容器集群管理系统，提供应用部署、维护、扩展机制等功能，利用Kubernetes能方便地管理跨机器运行容器化的应用，其主要功能如下：
1) 使用Docker对应用程序包装(package)、实例化(instantiate)、运行(run)。
2) 以集群的方式运行、管理跨机器的容器。
3) 解决Docker跨机器容器之间的通讯问题。
4) Kubernetes的自我修复机制使得容器集群总是运行在用户期望的状态。

我们从以下几方面来进行阐述：
1) Kubernetes的主要概念。
2) Kubernetes的架构以及组件交互。

## 1、主要概念
在实践之前，先来看看 Kubernetes 的几个重要概念，它们是组成 Kubernetes 集群的基石。
### **1.1、Cluster**
Cluster 是计算、存储和网络资源的集合，这些资源可以使GCE、vShpere、CoreOS、OpenShift、Azure等云平台，也可以直接运行在物理机上，Kubernetes 利用这些资源运行各种基于容器的应用。

### **1.2、Master**
Master 是 Cluster 的大脑，可以是物理机或者虚拟机，它的主要职责是调度，即决定将应用放在哪里运行。
> 为了实现高可用，可以运行多个 Master，本文的实践就是双Master架构。

```bash
[root@k8s-node1 dashboard]# kubectl get nodes
NAME        STATUS    ROLES         AGE       VERSION
k8s-node1   Ready     master,node   17d       v1.9.2+coreos.0
k8s-node2   Ready     master,node   17d       v1.9.2+coreos.0
k8s-node3   Ready     node          17d       v1.9.2+coreos.0
k8s-node4   Ready     node          15d       v1.9.2+coreos.0
```
### **1.3、Node**
Node由Master管理，负责监控并汇报容器的状态，并根据 Master 的要求管理容器的生命周期，可以是物理机或者是虚拟机。

### **1.4、Pod**
Pod 是 Kubernetes 的最小工作单元。每个 Pod 包含一个或多个容器。Pod 中的容器会作为一个整体被 Master 调度到一个 Node 上运行，其工作方式如下，
1) **运行单一容器**
运行单一容器是 Kubernetes 最常见的模型，这种情况下，只是将单个容器简单封装成 Pod。即便是只有一个容器，Kubernetes 管理的也是 Pod 而不是直接管理容器。
2) **运行多个容器**
将多个联系紧密的容器，而且需要直接共享资源的容器放到同一个pod里面。

> 正例：服务A更新volume共享数据，而服务B读取volume共享数据，那么这两个容器服务明显适合放到同一个Pod里面去，同时启动同时停止。
> 反例：Tomcat服务、Mysql服务，没必要每次重启应用，数据库需要跟着重启。

引入 Pod 主要基于下面两个目的：
1) **可管理性**。
有些容器天生就是需要紧密联系，一起工作。Pod 提供了比容器更高层次的抽象，将它们封装到一个部署单元中。Kubernetes 以 Pod 为最小单位进行调度、扩展、共享资源、管理生命周期。
2) **通信和资源共享**。
Pod 中的所有容器使用同一个网络 namespace，即相同的 IP 地址和 Port 空间。它们可以直接用 localhost 通信。同样的，这些容器可以共享存储，当 Kubernetes 挂载 volume 到 Pod，本质上是将 volume 挂载到 Pod 中的每一个容器。

Pod的生命周期可能是一下的一种，
1) 挂起（Pending）：Pod 已被 Kubernetes 系统接受，但有一个或者多个容器镜像尚未创建。等待时间包括调度 Pod 的时间和通过网络下载镜像的时间，这可能需要花点时间。
2) 运行中（Running）：该 Pod 已经绑定到了一个节点上，Pod 中所有的容器都已被创建。至少有一个容器正在运行，或者正处于启动或重启状态。
3) 成功（Successed）：Pod 中的所有容器都被成功终止，并且不会再重启。
4) 失败（Failed）：Pod 中的所有容器都已终止了，并且至少有一个容器是因为失败终止。也就是说，容器以非0状态退出或者被系统终止。
5) 未知（Unkonwn）：因为某些原因无法取得 Pod 的状态，通常是因为与 Pod 所在主机通信失败。

### 1.5、Controller
k8s通常不会直接创建pod，而是通过Controller来管理Pod的。Controller中定义了Pod的部署特性（[controller格式说明](#5 )），比如副本个数等，在哪个Node上运行等。为了满足业务场景需要，k8s提供了多种Controller，包括Deployment、ReplicaSet、DaemonSet、StatefulSet、Job等。

| 类型| 说明 | 状态 | 应用场景 |
| ------ | ------ | ------ | ------ |
| Deployment | 可以管理 Pod 的多个副本，并确保 Pod 按照期望的状态运行 | 无状态 | 最常用的 |
| ReplicaSet | 实现了 Pod 的多副本管理。使用 Deployment 时会自动创建 ReplicaSet | 无状态 | 通常不会用到 |
| DaemonSet | 每个 Node 最多只运行一个 Pod 副本 | 无状态 | Node单节点应用 |
| StatefuleSet | 保证Pod的每个副本在整个生命周期的名称是不可变的，并且会保证副本按照固定的顺序启动、更新或者删除 | 无状态 | zookeeper等有状态集群 |
| Job | 对比上述其他Controller长时间运行的，Job是运行结束就会被删除的应用。| 无状态 | 一次性任务 |

### 1.6、Service
Deployment可以部署多个副本，每个副本都有自己的IP，但是此时这些副本是无法被外界访问的。Service就是定义了外界访问一组特定Pod的方式，它有自己的IP和端口，Service为特定的Pod提供了负载均衡。

> Controller用于运行Pod，而访问容器则交给了Service来维护

### 1.7、Labels
Labels是用于区分Pod、Service、Replication Controller的key/value键值对，Pod、Service、Controller可以有多个label，但是每个label的key只能对应一个value。Labels是Service和Replication Controller运行的基础，主要功能有：
1) Controller使用labels来管理通过pod 模板创建的一组容器，这样Controller可以更加容易，方便地管理多个容器。
2) Service通过Labels来标识选择后端服务容器，从而将访问Service的请求转发给后端提供服务的多个容器

### 1.8、Namespace
Namespace 可以将一个物理的 Cluster 逻辑上划分成多个虚拟 Cluster，每个 Cluster 就是一个 Namespace。不同 Namespace 里的资源是完全隔离的。
集群默认创建了三个Namespace，如下
```bash
[root@k8s-node1 dashboard]# kubectl get namespace
NAME          STATUS    AGE
default       Active    17d
kube-public   Active    17d
kube-system   Active    17d
```
### 1.9、Endpoints
负责维护Service与Pod的映射关系，Service删除时，Endpoints也会被删除，并提供接口给API Server调用。

### 1.10、Volume
容器中的磁盘的生命周期是短暂的，这就带来了一系列的问题，
1. 当一个容器损坏之后，kubelet 会重启这个容器，但是文件会丢失-这个容器会是一个全新的状态；
2. 当很多容器在同一Pod中运行的时候，很多时候需要数据文件的共享。
Volume就是用来解决了这些问题，volume独立与容器，与Pod拥有相同的生命周期，Pod被删除，那么volume也会被删除。目前Volume支持的方式有：

- emptyDir
- hostPath
- secret
- rbd
- gce等云

### 1.11 PV/PVC/StorageClass
**介绍**
PersistentVolume（PV）
PV跟Volume类似，是由管理员配置好的一个集群存储块资源，它就像是集群中的一个节点，但独立于任何Pod。
目前PV支持的插件有：

- GCEPersistentDisk
- AWSElasticBlockStore
- AzureFile
- AzureDisk
- FC (Fibre Channel)
- FlexVolume
- Flocker
- NFS
- iSCSI
- RBD (Ceph Block Device)
- CephFS
- Cinder (OpenStack block storage)
- Glusterfs
- VsphereVolume
- Quobyte Volumes
- HostPath (仅用于单机测试)
- VMware Photon
- Portworx Volumes
- ScaleIO Volumes
- StorageOS
需要注意的是，上述插件只支持新存储区块，也就是这个快是没被占用的。
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem            # alpha，可以是Filesystem、Block
  accessModes:
    - ReadWriteOnce                 # 访问模式
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
```
> storageClassName将来会被废弃，请使用`volume.beta.kubernetes.io/mount-options`

accessModes目前支持的有以下模式：

- ReadWriteOnce
卷只允许单机读写
- ReadOnlyMany 
卷可以允许多台机器进行读
- ReadWriteMany 
卷可以允许多台机器进行读写

> 需要注意的是，一个卷不可以被同时申明成多个accessModes

PersistentVolumeClaim（PVC）
PVC是用户存储的请求。 它类似于pod，Pod消费Node主机上的资源(CPU/Memory)，而PVC消费的是PV上的资源（特定大小，以及读写模式）。

虽然，PVC允许用户使用PV，但是实际运用上，不同用户可能需要拥有不同属性的PV，要是由集群管理员来创建大量不同的PV，这无疑是巨大工作量，明显不合适，StorageClass就是用来这个问题。

StorageClass
StorageClass为管理员提供了一种描述他们提供的存储的“类”的方法，可以动态提供不同的PV。 
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gluster-vol-default
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://192.168.10.100:8080"
  restuser: ""
  secretNamespace: ""
  secretName: ""
allowVolumeExpansion: true
```

**Volume、PV和PVC的生命周期**
PV（Volume）和PVC之间的相互作用遵循这个生命周期:
```
Provisioning ——> Binding ——> Using——> Reclaiming ——> Recycling
```
1. Provisioning
目前，有两种方式进行PV供给：

- Static 静态供给
管理员创建多个PV，这些PV带着用户的真实数据，可以给集群用户有效地使用
- Dynamic 动态供给
当没有PV满足用户的PVC申明时，会根据定义中的StorageClasses来创建，规则如下：
a) 定义申明配置了StorageClasses，并且在API Server的准入控制`--admisson-control`中配置了`DefaultStorageClass`，那么会自动创建，否则将不会自动创建PV。
b) 没有StorageClasses的PV没有类，只能绑定到不需要特定类的PVC
2. Binding
当用户创建或者已经创建特定大小和明确访问模式时，集群会循环来监控这些新的PVC，如果找到匹配的PV时，会将PV跟PVC进行绑定。要是没有匹配，会根据定义动态配置PV，然后将他们绑定（这里可能会出现Volume空间不足的情况）。
一旦PVC进行绑定，那么PVC跟PV的映射关系就不可变了，PV此时被PVC独占。

> 如果空间只有50G，但是PVC要求分配100G，那么PVC会无限次进行绑定，直到有足够的空间，绑定才会停止。

3. Using
Pod可以使用PVC作为Volume，如下：
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: dockerfile/nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
```

4. Reclaiming
当用户完成使用Volume时，可以使用API来声明删除PVC，但此时PV未被真正删除（此时状态是`Released`，处于不可用状态，不能再被用于绑定），而是根据一定的策略操作后才真正释放。目前支持的策略有：Retained, Recycled or Deleted.

Retain
Retain策略允许用户手动回收资源，其步骤是：
1) 删除对应PV对象。但需要注意的是，外部存储资源并未被删除。
2）有必要的话登录云平台删除对应资源。
3）若是还想复用对应的资源，那么创建新的PV将他们关联起来。

Delete
Delete策略将同时删除PV以及对应的资源，但需要注意的是，不是所有的资源都可以被同步删除的，比如NFS就不是删除。
> 需要注意的是，使用Aws、GCE、Cinder等第三方卷时，Reclaim的策略默认是删除，请根据需要进行更改。

5. Recycle
Recycle策略目前已经废弃，请使用动态卷。

定义好PVC后，但是后来却发现PV不够用了，那么能否动态扩展能呢？答案是肯定的，但前提是下面两个条件都满足：
- API Server的准入控制`--admission-control`配置了`PersistentVolumeClaimResize`；
- StorageClass的allowVolumeExpansion配置成`true`。

一旦满足上述两个，那么你就可以修改PVC的定义，扩大存储空间，记得使用：
```bash
kubectl apply -f pvc.yaml
```
[persistent-volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes)

## 2、架构以及组件交互
在开始了解之前，我们来看看前面的集群总体架构([cluster](#1 ))。
![image](https://user-images.githubusercontent.com/5570216/36774959-08dc43fe-1c9b-11e8-89e6-d8ba66c002dc.png)
我们将从以下几个方面来展开集群的架构分析：
1) Master上的组件
2) Node上的组件
3) Master、Node组件之间的交互

#### **2.1.1、Authentication/Authorization/Admission Control**
Kubernetes集群的所有操作基本上都是通过kube-apiserver这个组件进行的，它提供HTTP RESTful形式的API供集群内外客户端调用。但值得注意的是，
1. 认证授权过程只存在HTTP请求；
2. HTTP请求不会进行授权认证。

一个HTTPS API请求需要经过三个阶段，认证->授权->准入控制，这样一定程度上提高了集群的安全性，但是k8s权衡的更多是资源方面的管理。
**Authentication**
对于访问 API 来说提供了两个步骤的安全措施：认证和授权。认证解决用户是谁的问题，授权解决用户能做什么的问题。通俗地讲，认证就是验证用户名以及用户密码，授权就是检查该用户是否拥有权限访问请求的资源。

目前，1.9版本提供了一下的[认证方式](https://kubernetes.io/docs/admin/authentication):
1) 客户端证书
客户端证书认证叫作TLS双向认证，也就是服务器客户端互相验证证书的正确性，在都正确的情况下协调通信加密方案。
为了使用这个方案，api－server需要用－client－ca－file＝选项来开启。CA_CERTIFICATE_FILE肯定包括一个或者多个认证中心，可以被用来验证呈现给api－server的客户端证书。客户端证书的／CN将作为用户名。

2) 静态Token文件
用token唯一标识请求者，只要apiserver存在该token，则认为认证通过，但是如果需要新增Token，则需要重启kube-apiserver组件，实际效果不是很好。
当在命令行指定- -token-auth-file=SOMEFILE选项时，API服务器从文件中读取 bearer tokens。目前，tokens持续无限期。
令牌文件是一个至少包含3列的csv文件： token, user name, user uid，后跟可选的组名。注意，如果您有多个组，则列必须是双引号，例如
```bash
token,user,uid,"group1,group2,group3"
```

3) 引导Token
目前这个特性还是alpha特性。为了能够在新的集群中使用bootstrapping认证。Kubernetes包括一种动态管理的Bearer(持票人) token，这种token以Secrets的方式存储在kube-system命名空间中，在这个命名空间token可以被动态的管理和创建。Controller Manager有一个管理中心，如果token过期了就会删除。

创建的token证书满足[a-z0-9]{6}.[a-z0-9]{16}格式，Token的第一部分是一个Token ID，第二部分是token的秘钥。你需要在http协议头中加上类似的信息：
```bash
Authorization: Bearer 781292.db7bc3a58fc5f07e
```
如果要使用Bootstrap，需要在API Sever中开启--experimental-bootstrap-token-auth。同时必须在Controller Manager中开启管理中心的设置--controllers=*,tokencleaner。

在使用kubeadm部署Kubernetes时，kubeadm会自动创建默认token，可通过kubeadm token list命令查询。

4) 静态文件密码
静态密码的方式是提前在某个文件中保存了用户名和密码的信息，然后在 apiserver 启动的时候通过参数 –basic-auth-file=SOMEFILE 指定文件的路径。apiserver 一旦启动，加载的用户名和密码信息就不会发生改变，任何对源文件的修改必须重启 apiserver 才能生效。
> 这种方式不灵活，不推荐使用

5) Service Account Token
Service Account 是面向 namespace 的，每个 namespace 创建的时候，kubernetes 会自动在这个 namespace 下面创建一个默认的 Service Account；并且这个 Service Account 只能访问该 namespace 的资源。Service Account 和 pod、service、deployment 一样是 kubernetes 集群中的一种资源，用户也可以创建自己的 serviceaccount。

6) OpenID Connect Tokens 认证
OpenID Connect 是一些由OAuth2提供商支持的OAuth2，特别是Azure Active Directory，Salesforce和Google。OAuth2的协议的主要扩展是增加一个额外字段，返回了一个叫ID token的access token。这个token是被服务器签名的JSON Web Token (JWT) ，具有众所周知的字段，比如用户的email。
为了识别用户，验证使用来自OAuth2 token响应的id_token (而不是 access_token)作为bearer token。

7) Webhook Token 认证
Webhook Token 认证方式可以让用户使用自己的认证方式，用户只需要按照约定的请求格式和应答格式提供 HTTPS 服务，当用户把 Bearer Token 放到请求的头部，kubernetes 会把 token 发送给事先配置的地址进行认证，如果认证结果成功，则认为请求用户合法。 这种方式下有两个参数可以配置：
```bash
–authentication-token-webhook-config-file ：kubeconfig 文件说明如果访问认证服务器
–authentication-token-webhook-cache-ttl ：认证结果要缓存多久，默认是两分钟 
```
这种方式下，自定义认证的请求和应答都有一定的格式，具体的规范请参考 官方文档的说明 。

8) 认证代理
在API Server启动时指定下面参数
```bash
--requestheader-username-headers=X-Remote-User
--requestheader-group-headers=X-Remote-Group
--requestheader-extra-headers-prefix=X-Remote-Extra-
# 为了防止头部欺骗，证书是必选项
--requestheader-client-ca-file
# 设置允许的CN列表。可选。
--requestheader-allowed-names
```
9) Keystone Password 认证
需要API Server在启动时指定--experimental-keystone-url=<AuthURL>，而https时还需要设置--experimental-keystone-ca-file=SOMEFILE。
> 此方法对于已经使用 openstack 来搭建 Iaas 平台的公司比较适用，直接使用 keystone 可以保证 Iaas 和 Caas 平台保持一致的用户体系。

10) 匿名请求
如果请求没有通过以上任何方式的认证，正常情况下应该是直接返回 401 错误。但是 kubernetes 还提供另外一种选择，给没有通过认证的请求一个特殊的用户名 system:anonymous 和组名 system:unauthenticated 。

11) 用户模拟
通过在伪装请求header，可以达到通过认证的目的，值得注意的是，被模拟用户需要拥有被模拟的权限。

这样的话，可以跟下面要讲的授权结合起来，为匿名请求设置一些特殊的权限，比如只能读取当前 namespace 的 pod 信息，方便用户访问。

如果使用AlwaysAllow以外的认证模式，则匿名请求默认开启，但可用--anonymous-auth=false禁止匿名请求。

**Authorization**
授权主要是用于对集群资源的访问控制，通过检查请求包含的相关属性值，与相对应的访问策略相比较，API请求必须满足某些策略才能被处理。跟认证类似，Kubernetes也支持多种授权机制，并支持同时开启多个授权插件（只要有一个验证通过即可）, 目前Kubernetes支持授权插件有：
1) ABAC
使用ABAC授权需要API Server配置
```
--authorization-mode=ABAC
--authorization-policy-file=SOME_FILENAME #文件格式为每行一个json对象。
```
其中--authorization-policy-file的格式如下
```json
{
    "apiVersion": "abac.authorization.kubernetes.io/v1beta1",
    "kind": "Policy",
    "spec": {
        "group": "system:authenticated",
        "nonResourcePath": "*",
        "readonly": true
    }
}
{
    "apiVersion": "abac.authorization.kubernetes.io/v1beta1",
    "kind": "Policy",
    "spec": {
        "group": "system:unauthenticated",
        "nonResourcePath": "*",
        "readonly": true
    }
}
{
    "apiVersion": "abac.authorization.kubernetes.io/v1beta1",
    "kind": "Policy",
    "spec": {
        "user": "admin",
        "namespace": "*",
        "resource": "*",
        "apiGroup": "*"
    }
}
```
> 同样的，这种授权方式不灵活，每次变更都得重启API Server。

2) RBAC
RBAC 的授权策略可以利用 kubectl 或者 Kubernetes API 直接进行配置。RBAC 可以授权给用户，让用户有权进行授权管理，这样就可以无需接触节点，直接进行授权管理。RBAC 在 Kubernetes 中被映射为 API 资源和操作。
因为 Kubernetes 社区的投入和偏好，相对于 ABAC 而言，RBAC 是更好的选择，RBAC基本概念包括：
Role
角色是一系列权限的集合，例如一个角色可以包含读取 Pod 的权限和列出 Pod 的权限， ClusterRole 跟 Role 类似，但是可以在集群中到处使用（ Role 是 namespace 一级的）。
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
```
Role Binding
RoleBinding 把角色映射到用户，从而让这些用户继承角色在 namespace 中的权限。
```yaml
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
另外，还有cluster roles和cluster role binding。cluster role和cluster role binding方法跟role和role binding一样，但区别是：
- rolebinding是用户级别的；
- clusterrolebinding是集群级别的，不限定特定的namespace。
详细差别请访问[role binding与clsuter role binding](https://kubernetes.io/docs/admin/authorization/rbac/#rolebinding-and-clusterrolebinding).

3) Webhook
使用WebHook授权需要API Server配置`--authorization-webhook-config-file=SOME_FILENAME`和`--runtime-config=authorization.k8s.io/v1beta1=true`，配置文件格式同kubeconfig，如
```yaml
# clusters refers to the remote service.
clusters:
  - name: name-of-remote-authz-service
    cluster:
      certificate-authority: /path/to/ca.pem      # CA for verifying the remote service.
      server: https://authz.example.com/authorize # URL of remote service to query. Must use 'https'.

# users refers to the API Server's webhook configuration.
users:
  - name: name-of-api-server
    user:
      client-certificate: /path/to/cert.pem # cert for the webhook plugin to use
      client-key: /path/to/key.pem          # key matching the cert

# kubeconfig files require a context. Provide one for the API Server.
current-context: webhook
contexts:
- context:
    cluster: name-of-remote-authz-service
    user: name-of-api-server
  name: webhook
```
API Server请求Webhook的格式为：
```json
{
  "apiVersion": "authorization.k8s.io/v1beta1",
  "kind": "SubjectAccessReview",
  "spec": {
    "resourceAttributes": {
      "namespace": "kittensandponies",
      "verb": "get",
      "group": "unicorn.example.org",
      "resource": "pods"
    },
    "user": "jane",
    "group": [
      "group1",
      "group2"
    ]
  }
}
```
而Webhook server需要返回授权的结果，允许(allowed=true)或拒绝(allowed=false)：
```json
{
  "apiVersion": "authorization.k8s.io/v1beta1",
  "kind": "SubjectAccessReview",
  "status": {
    "allowed": true
  }
}
```
4) Node
仅v1.7版本以上支持Node授权，配合NodeRestriction准入控制来限制kubelet仅可访问node、endpoint、pod、service以及secret、configmap、PV和PVC等相关的资源，配置方法为
```
--authorization-mode=Node,RBAC --admission-control=...,NodeRestriction,...
```
注意，kubelet认证需要使用system:nodes组，并使用用户名system:node:<nodeName>。

> 请通过API Server配置集群的授权类型`--authorization-mode=Type`,其中Type为上述任一种，默认是RBAC

--authorization-mode=Webhook
5) AlwaysDeny/AlwaysAllow
Kubernetes还支持AlwaysDeny和AlwaysAllow模式，其中AlwaysDeny仅用来测试，而AlwaysAllow则允许所有请求（会覆盖其他模式）。
可以在API Server中通过下面的参数进行配置：
```
--authorization-mode=AlwaysAllow
--authorization-mode=AlwaysDeny
```
Kubernetes授权处理以下的请求属性：
1) user, group, extra
2) API、请求方法（如get、post、update、patch和delete）和请求路径（如/api）
3) 请求资源和子资源
4) Namespace
5) API Group
如果授权成功，则用户的请求会发送到准入控制模块做进一步的请求验证；对于授权失败的请求则返回HTTP 403。
> 通过合理的权限管理，能够保证系统的安全可靠。

**[Admission Control](https://kubernetes.io/docs/admin/admission-controllers/)**
当请求通过了前面的认证和授权之后，还需要经过准入控制处理通过之后，apiserver 才会处理这个请求。Admission Control 有一个准入控制列表这个，这个列表可以在启动API Server的时候配置，
```bash
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```
也可以通过命令行[动态设置](https://kubernetes.io/docs/admin/extensible-admission-controllers/)选择执行哪几个准入控制器。只有所有的准入控制器都检查通过之后，apiserver 才执行该请求，否则返回拒绝。

准入控制器的作用

在kubernetes中，一些高级特性正常运行的前提条件为，将一些准入模块处于enable状态，如果不适当的配置准入控制模块，某些功能也不会正常的生效。

准入控制器介绍

| 名称 | 作用 | 说明 |
| --- | --- | --- |
| AlwaysAdmit | 允许所有请求 |  |
| AlwaysDeny | 拒绝所有请求 | |
| AlwaysPullImages | 强制设置Pod拉取镜像策略为Always | 能够保证私有镜像只能被有拉取权限的使用者使用 |
| DenyExecOnPrivileged | 截所有想在privileged container上执行命令的请求 | 可以限制特定用户在privileged container上执行命令 |
| DenyEscalatingExec | 禁止那些通过主机执行而获得privileges去执行exec和attach Pod的命令 |  |
| ImagePolicyWebhook | 通过webhook决定image策略，需要同时配置–admission-control-config-file |  |
| ServiceAccount | 为运行在pod内的进程添加了相应的认证信息 |  |
| ResourceQuota | 配额控制 | 主要针对的是Namespace |
| LimitRanger | 配额控制 | 主要针对的是Pod和Container |
| SecurityContextDeny | 禁止创建设置了 Security Context 的 pod。 |  |
| NamespaceLifecycle | 确保处于termination状态的namespace不再接收新的对象创建请求，并拒绝请求不存在的namespace。 |  |
| InitialResources | 根据镜像的历史使用记录，为容器设置默认资源请求和限制 |  |
| DefaultStorageClass | 为PVC设置默认StorageClass |  |
| DefaultTolerationSeconds | 设置Pod的默认forgiveness toleration为5分钟 |  |
| PodSecurityPolicy | 使用Pod Security Policies时必须开启 |  |
| NodeRestriction | 限制kubelet仅可访问node、endpoint、pod、service以及secret、configmap、PV和PVC等相关的资源 |  |

> 若是k8s集群中使用到任何对象，都必须启用对应插件，比如集群用到ResourceQuota对象，那么要配置ResourceQuota。

#### **2.1.2、API Server**
API Server 提供 HTTP/HTTPS RESTful API，即 Kubernetes API。API Server 是 Kubernetes Cluster 的前端接口，各种客户端工具（CLI 或 UI）以及 Kubernetes 其他组件可以通过它管理 Cluster 的各种资源。
#### **2.1.3、Scheduler**
Scheduler 负责决定将 Pod 放在哪个 Node 上运行。Scheduler 在调度时会充分考虑 Cluster 的拓扑结构，当前各个节点的负载，以及应用对高可用、性能、数据亲和性的需求。
#### **2.1.4、Controller Manager**
Controller Manager作为集群内部的管理控制中心，负责集群内的Node、Pod副本、服务端点（Endpoint）、命名空间（Namespace）、服务账号（ServiceAccount）、资源定额（ResourceQuota）的管理，当某个Node意外宕机时，Controller Manager会及时发现并执行自动化修复流程，确保集群始终处于预期的工作状态。

**Node Controller**
kubelet在启动时会通过API Server注册自身的节点信息，并定时向API Server汇报状态信息，API Server接收到信息后将信息更新到etcd中。
Node Controller通过API Server实时获取Node的相关信息，实现管理和监控集群中的各个Node节点的相关控制功能。

**Replication Controller**
副本控制器保证集群中一个RC所关联的Pod副本数始终保持预设值，其职责是，
1. 只有当Pod的重启策略是Always的时候（RestartPolicy=Always），副本控制器才会管理该Pod的操作（创建、销毁、重启等）。
2. RC中的Pod模板就像一个模具，一旦Pod被创建，无论模板如何变化，也不会影响到已经创建的Pod。
3. Pod可以通过修改label来脱离RC的管控，该方法可以用于将Pod从集群中迁移，数据修复等调试。
4. 删除一个RC不会影响它所创建的Pod，如果要删除Pod需要将RC的副本数属性设置为0。

1、Replication Controller的职责
1. 确保集群中有且仅有N个Pod实例，N是RC中定义的Pod副本数量。
2. 通过调整RC中的spec.replicas属性值来实现系统扩容或缩容。
3. 通过改变RC中的Pod模板来实现系统的滚动升级。
> 不要越过RC创建Pod，因为RC可以实现自动化控制Pod，提高容灾能力。

2、Replication Controller的应用场景

| 场景 | 说明 | 操作命令 |
| ------ | ------ | ------ |
| 重新调度 | 当发生节点故障或Pod被意外终止运行时，可以重新调度保证集群中仍然运行指定的副本数。| |
| 弹性伸缩 | 通过手动或自动扩容代理修复副本控制器的spec.replicas属性，可以实现弹性伸缩。| kubectl scale |
| 滚动更新 | 创建一个新的RC文件，通过kubectl 命令或API执行，则会新增一个新的副本同时删除旧的副本，当旧副本为0时，删除旧的RC。| [kubectl rolling-update](https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/) |

**Endpoints Controller**
Endpoints主要是用来映射Service与Pod的，它们之间的关系如下：
![20170721232926780](https://user-images.githubusercontent.com/5570216/36831263-fa502054-1d61-11e8-89d5-d7cc3f9efb27.png)
Endpoints表示了一个Service对应的所有Pod副本的访问地址，而Endpoints Controller负责生成和维护所有Endpoints对象的控制器。它负责监听Service和对应的Pod副本的变化。

- 如果监测到Service被删除，则删除和该Service同名的Endpoints对象；
- 如果监测到新的Service被创建或修改，则根据该Service信息获得相关的Pod列表，然后创建或更新Service对应的Endpoints对象。
- 如果监测到Pod的事件，则更新它对应的Service的Endpoints对象。

kube-proxy进程获取每个Service的Endpoints，实现Service的负载均衡功能。

**Service Controller**
Service Controller是属于kubernetes集群与外部的云平台之间的一个接口控制器。Service Controller监听Service变化，如果是一个LoadBalancer类型的Service，则确保外部的云平台上对该Service对应的LoadBalancer实例被相应地创建、删除及更新路由转发表。

**Namespace Controller**
用户通过API Server可以创建新的Namespace并保存在etcd中，Namespace Controller定时通过API Server读取这些Namespace信息。

如果Namespace被API标记为优雅删除（即设置删除期限，DeletionTimestamp）,则将该Namespace状态设置为“Terminating”,并保存到etcd中。同时Namespace Controller删除该Namespace下的ServiceAccount、RC、Pod等资源对象。

**ResourceQuota Controller**
资源配额管理确保指定的资源对象在任何时候都不会超量占用系统物理资源。其支持三个层次的资源配置管理：
1）容器级别：对CPU和Memory进行限制
2）Pod级别：对一个Pod内所有容器的可用资源进行限制
3）Namespace级别：包括
  - Pod数量
  - Replication Controller数量
  - Service数量
  - ResourceQuota数量
  - Secret数量
  - 可持有的PV（Persistent Volume）数量
说明：
k8s配额管理是通过Admission Control（准入控制）来控制的；
Admission Control提供两种配额约束方式：LimitRanger和ResourceQuota；
LimitRanger作用于Pod和Container；
ResourceQuota作用于Namespace上，限定一个Namespace里的各类资源的使用总额。

**ServiceAccount Controller**
用于创建ServiceAccount
```yaml
---
# config another ServiceAccount for admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-dashboard-admin
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kubernetes-dashboard
```
#### **2.1.5、kubectl**
客户端工具，用来操作API Server，API Server响应对应的命令结果，从而达到对kubernetes集群的管理。
#### **2.2.1、Kubelet**
1) 负责Node节点上pod的创建、修改、监控、删除等全生命周期的管理
2) 定时上报本Node的状态信息给API Server。
3) kubelet是Master API Server和Node之间的桥梁，接收Master API Server分配给它的commands和work，与持久性键值存储etcd、file、server和http进行交互，读取配置信息。

具体的工作如下：
1) 设置容器的环境变量、给容器绑定Volume、给容器绑定Port、根据指定的Pod运行一个单一容器、给指定的Pod创建network 容器。
2) 同步Pod的状态、同步Pod的状态、从cAdvisor获取Container info、 pod info、 root info、 machine info。
3) 在容器中运行命令、杀死容器、删除Pod的所有容器。

#### **2.2.2、cAdvisor**
kubelet通过cAdvisor获取本节点信息及容器的数据。cAdvisor为谷歌开源的容器资源分析工具，默认集成到kubernetes中。

cAdvisor自动采集CPU,内存，文件系统，网络使用情况，容器中运行的进程，默认端口为4194。可以通过Node IP+Port访问。

#### **2.2.3、Kube-proxy**
Proxy是为了解决外部网络能够访问跨机器集群中容器提供的应用服务而设计的，运行在每个Node上。Proxy提供TCP/UDP sockets的proxy，每创建一种Service，Proxy主要从etcd获取Services和Endpoints的配置信息（也可以从file获取），然后根据配置信息在Minion上启动一个Proxy的进程并监听相应的服务端口，当外部请求发生时，Proxy会根据Load Balancer将请求分发到后端正确的容器处理。
Proxy不但解决了同一主宿机相同服务端口冲突的问题，还提供了Service转发服务端口对外提供服务的能力，Proxy后端使用了随机、轮循负载均衡算法。
