### ISSUE TITLE
k8s/关于Chart的目录结构

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#21]
Chart实际上由一系列文件组成，这些文件描述了 Kubernetes 部署应用时所需要的资源，比如 Service、Deployment、PVC、Secret、ConfigMap 等。

Chart可以简单到只有一个服务，也可以复杂到N个服务，比如包含 HTTP Servers、 Database、MQ、Cache 等的应用。但无论如何，Chart按照预定义的目录结构将这些文件打包成一个tar。这个tar在使用`helm install`安装时，会自动下载到`~/.helm/cache/archive`目录，我们来看看前面部署的PXC集群。
```bash
[root@k8s-node1 ~]# ls ~/.helm/cache/archive
percona-xtradb-cluster-0.1.3.tgz
```
> Helm约定tar的文件名字按照`name-version.tgz`的命名形式命名。

我们将tar解压到根目录`~`，并逐个展开描述。
```bash
[root@k8s-node1 ~]# tar -zxvf ~/.helm/cache/archive/percona-xtradb-cluster-0.1.3.tgz -C ~
[root@k8s-node1 ~]# tree ~/percona-xtradb-cluster/
/root/percona-xtradb-cluster/
├── Chart.yaml                          # Required，Chart的基本信息，
├── files                               # Optional，文件信息
│   ├── entrypoint.sh
│   ├── functions.sh
│   └── node.cnf
├── OWNERS                              # Optional，共享者列表
├── README.md                           # Optional，使用说明文档
├── requirements.yaml                   # Optional，依赖Chart
├── templates                           # Optional，yaml模板
│   ├── config-map_mysql-config.yaml
│   ├── config-map_startup-scripts.yaml
│   ├── _helpers.tpl
│   ├── NOTES.txt                       # Optional， 包含简单使用的文本文件
│   ├── secrets.yaml
│   ├── service-metrics.yaml
│   ├── service-percona.yaml
│   ├── service-repl.yaml
│   ├── statefulset.yaml
│   └── tests                           # 测试yaml
│       ├── pxc-test-cm.yaml
│       └── pxc-test.yaml
└── values.yaml                         # Required，Chart的默认配置值

3 directories, 18 files
```

## **Chart.yaml**
```bash
[root@k8s-node1 ~]# cat percona-xtradb-cluster/Chart.yaml 
appVersion: 5.7.19  # 通常是应用的版本号，跟version没关系
description: free, fully compatible, enhanced, open source drop-in replacement for
  MySQL with Galera Replication (xtradb)    # chart描述
engine: gotpl
home: https://www.percona.com/
icon: https://www.percona.com/sites/all/themes/percona2015/logo.png
keywords:
- mysql
- percona
- database
- sql
- xtradb
- galeras
- wsrep
maintainers:
- email: username.taken@gmail.com
  name: paulczar
name: percona-xtradb-cluster    # 名字，Required
sources:
- https://github.com/kubernetes/charts
- https://github.com/percona-lab/percona-docker/
version: 0.1.3                  # Chart版本，Required
```
> 需要注意的是，未知的字段都会被丢掉。

## **README.md**
Markdown 格式的 README 文件，此文件为可选，通常都是一些使用说明。

## **LICENSE**
文本文件，描述 chart 的许可信息，此文件为可选。

## **OWNERS**
共享者信息，此文件可选。

## **Values**
Values包含了`values.yaml`、helm预定义value、全局参数global，这些值可以用于渲染templates，requirements.yaml等文件。
**vlues.yaml**
Chart支持在安装的时通过参数`--set`进行定制化配置，而`values.yaml`则提供了这些配置参数的默认值。
```
mysql:
  enabled: true
tags:
- tag1: false
  tag2: true
  tag3: true
```

**预定义value**
helm还有内置的一些大小写敏感的参数，比如

| name | 说明 |
| --- | --- |
| Release.Name | 发布版本的名称，比如通过`-n`参数指定 |
| Release.Time | 最后一次更新时间 |
| Release.Namespace | 发布对应的namespace |
| Release.Service | 管理发布的服务，通常是tiller |
| Release.IsUpgrade | 确定当前操作是更新还是回滚 |
| Release.IsInstall | 确定当前操作是安装操作 |
| Release.Revision | 修订版本号，默认1，每次使用`upgrade`更新自增 |
| Chart | `Chart.yaml`文件的内容 |
| \|--Chart.Version | chart版本号 |
| \|--Chart.Maintainers | chart维护人 |
| Files | 通常是一些非模板文件，可通过`{{index .Files "file.name"}}`、`{{.Files.Get name}}`、`{{.Files.GetString name}}`获取 |
| Capabilities | 类似于map结构 |

**Global value**
可以通过`global`节点定义参数，这些参数对于所有charts都可以通过`.Values.gloal.xxx`访问。
```
global:
  app: mysql
mysql:
  enabled: true
tags:
- tag1: false
  tag2: true
  tag3: true
```

## **requirements.yaml**
列出Chart的依赖，通常其格式如下。
```yaml
dependencies:
- name: apache                                      # Requchart的名字
  version: 1.2.3                                    # Required，chart版本
  repository: http://example.com/charts             # Required，完整的chart repo地址
- name: mysql
  version: 3.2.1
  repository: http://another.example.com/charts
  alias: xxxx                                       # 1
  tags:                                             # 2
  - tag1
  - tag2
  conditions: mysql.enabled
- name: mysql
  version: 3.2.1
  repository: http://another.example.com/charts
  alias: yyy                                        # 1   
  import-values:                                    # 2                  
  - child:
    parent:
  tags:                                             # 3
  - tag1
  - tag3
  conditions: mysql2.enabled 
```
(1)、Optional，可以通过字段`alias`声明Chart的别名，即使同一依赖也可以定义不同别名。
(2)、Optional，将依赖的Chart值直接导入到当前`values.yaml`里。
(3)、Optional，默认地，如果没有定义`tags`和`conditions`，所有的Chart都会生效。但是一旦他们被定义，那么会按照下面规则进行判断加载，
condition - 如果申明了一个或多个条件(,分割)，那么会判断`values.yaml`文件里面相关的值，如果任一条件有定义，且其值有true，那么Chart会生效，否则不生效。
tag - 跟condition类型，如果条件列表任一条件定义并且为true，即生效。
乍看起来，conditions和tags的作用是一样的，我们来看看两者的差别。
a)、**Conditions 优先于 Tags**，若是第一个condition为true，后续的条件都将失效。
b)、俩者都必须在`values`里面定义。
```java
if values[any(condition)]; then
    conditions effect.
elif values[any(tag)]; then
    tags effect.
fi
```

上面例子Chart的加载情况如下，
- 即使是tags.tag1=false，但是conditions会盖掉tags，所以Chart`mysql`会被加载。
- 尽管使用了`mysql2.condition`，但是其值未声明赋值，所以会判断tags，并找到tags.tag3=true，所以`alias=yyyy`的Chart会被加载。

一旦定义了依赖文件，我们可以运行`helm dependency update`来下载相关依赖的Chart(s)，并存放到目录`charts`。
```
[root@k8s-node1 percona-xtradb-cluster]# cat << EOF > requirements.yaml
dependencies:
- name: filebeat                            # Requchart的名字
  version: 0.2.0                            # Required，chart版本
  repository: https://kubernetes-charts.storage.googleapis.com  # Required，完整的chart repo地址
EOF
```
> 此处我们自己什么requirements.yaml文件

执行命令更新依赖
```
[root@k8s-node1 percona-xtradb-cluster]# helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading filebeat from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
```
依赖Chart已经下载成功，并存放到目录`charts`下。
```
[root@k8s-node1 percona-xtradb-cluster]# tree .
.
├── charts
│   └── filebeat-0.2.0.tgz
......
```

## **templates**
所有的模板文件都存在`templates`目录下，每当Helm渲染charts时，模板引擎会读取该目录填所有的文件，通常有俩种方式可以向模板传递变量。
- 在values.yaml文件里面定义的默认值
- 在使用`helm install --values=yourconfig.yaml`时自定义Yaml文件

需要注意的是，
1. 如果提供自定义值时，values.yaml中响应定义的值会被覆盖掉。
2. 如果在使用`helm update`或者`helm install`命令传递参数`--set`，那么这些参数会在客户端自动格式化成Yaml文件。

## **templates files**
Helm 采用了 Go 语言的模板来编写 chart。Go 模板非常强大，支持变量、对象、函数、流控制等功能。下面我们通过解析 templates/secrets.yaml 快速学习模板。
```go
[root@k8s-node1 ~]# cat percona-xtradb-cluster/templates/secrets.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "percona-xtradb-cluster.fullname" . }}  # 1
  labels:
    app: {{ template "percona-xtradb-cluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"         # 2
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}                        # 3
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.xtraBackupPassword }}
  xtrabackup-password:  {{ .Values.xtraBackupPassword | b64enc | quote }}
  {{ else }}
  xtrabackup-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
```
从结构看，文件的内容非常像 Secret 配置，只是大部分属性值变成了Go模板语法{{ xxx }}，我们来看看这些语法的作用。
(1). `{{ template "percona-xtradb-cluster.fullname" . }}`定义 Secret 的 name。
关键字 template 的作用是引用一个子模板 mysql.fullname。这个子模板是在 templates/_helpers.tpl 文件中定义的。
```
[root@k8s-node1 ~]# cat percona-xtradb-cluster/templates/_helpers.tpl 
{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "percona-xtradb-cluster.name" -}}
{{- default "pxc" .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "percona-xtradb-cluster.fullname" -}}
{{- $name := default "pxc" .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```
这个模板定义也还算简单明了，声明了两个变量，其默认值都是`pxc`，但是会被`.Values.nameOverride`覆盖。这里不打算进一步展开Go的语法说明，但是需要注意的是，
- **如果有一些信息会在多个模板使用，那么建议统一定义在`templates/_helpers.tpl`里面，然后使用template函数获取。
- **所有资源的名称都应该保持一致，比如统一使用`fullname`**
(2). Chart和Release都是Helm预定义的对象，上面有所描述。
(3). 这里使用了if-else流程来判断Values预定义对象是否有申明相对应的字段。

这里我们总结一下，模板最大的好处就是将Chart参数化，通过values.yaml可以灵活定制应用。
# 参考资料
[Helm Guide](https://docs.helm.sh/developing_charts/)
