### ISSUE TITLE
k8s/如何开发Chart

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#22]
尽管k8s社区给我们提供了许多的官方Chart，但实际上我们还是需要开发自己的Chart，今天将按照如下步骤来开发Chart，
1. 创建chart
2. 调试chart
3. 安装chart
4. 发布chart

# 创建 chart
执行 helm create mychart 的命令创建 chart mychart：
```bash
[root@k8s-node1 ~]# helm create inf-chart-demo
Creating inf-chart-demo
[root@k8s-node1 ~]# tree inf-chart-demo/ -L 2
inf-chart-demo/
├── charts
├── Chart.yaml
├── templates
    ├── deployment.yaml
    ├── _helpers.tpl
    ├── ingress.yaml
    ├── NOTES.txt
    └── service.yaml
└── values.yaml

2 directories, 7 files
```
发现 Helm 会帮我们创建目录 `inf-chart-demo`，并生成了相关必要的 chart 文，这样我们就可以在此基础上开发 chart 了。

新建的 chart 默认包含一个 nginx 应用示例，`values.yaml` 内容如下：
```yaml
[root@k8s-node1 ~]# cat inf-chart-demo/values.yaml 
# Default values for inf-chart-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
```

> 任何的熟悉都是从模仿开始，建议多参考[官方chart](https://github.com/kubernetes/charts)模板，里面包含了大量的实践，完全可以让我们少走一些弯路。

# 调试 chart
开发Chart就跟我们开发普通的应用程序一样，少不了要调试，helm提供了debug工具：`helm lint`、`helm install --dry-run chart-name --debug`

## helm lint
helm lint 会检测 chart 的语法，报告错误以及给出建议。
```
[root@k8s-node1 ~]# helm lint inf-chart-demo
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```
加入我们修改一下values.yaml文件，将`repository: nginx`改成`repository nginx`，并重新执行`lint`。
```
[root@k8s-node1 ~]# helm lint inf-chart-demo
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

Error: 1 chart(s) linted, 1 chart(s) failed
```

## helm install --dry-run chart-name --debug
`helm install --dry-run inf-chart-demo --debug`会模拟安装 chart，并输出每个模板生成的 YAML 内容。
```
[root@k8s-node1 ~]# helm install --dry-run inf-chart-demo --debug
[debug] Created tunnel using local port: '36884'

[debug] SERVER: "127.0.0.1:36884"

[debug] Original chart version: ""
[debug] CHART PATH: /root/inf-chart-demo

NAME:   dunking-crocodile
REVISION: 1
RELEASED: Thu May 17 09:33:54 2018
CHART: inf-chart-demo-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []

HOOKS:
MANIFEST:

---
# Source: inf-chart-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dunking-crocodile-inf-chart-demo
  labels:
    app: inf-chart-demo
    chart: inf-chart-demo-0.1.0
    release: dunking-crocodile
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: inf-chart-demo
    release: dunking-crocodile
---
# Source: inf-chart-demo/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dunking-crocodile-inf-chart-demo
  labels:
    app: inf-chart-demo
    chart: inf-chart-demo-0.1.0
    release: dunking-crocodile
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inf-chart-demo
      release: dunking-crocodile
  template:
    metadata:
      labels:
        app: inf-chart-demo
        release: dunking-crocodile
    spec:
      containers:
        - name: inf-chart-demo
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
```
我们可以检测输出的各个k8s文件，判断是否与预期的相符。

# 安装Chart
Helm 支持四种安装方法：
1. `仓库`安装，例如：helm install stable/nginx
2. `tar`安装，例如：helm install ./nginx-1.2.3.tgz
3. `本地目录`安装，例如：helm install ~/inf-chart-demo
4. `URL`安装，例如：`helm install https://example.com/charts/nginx-1.2.3.tgz`

这里我们使用第三种本地目录来安装：
```bash
[root@k8s-node1 ~]# helm install ~/inf-chart-demo/
NAME:   virtuous-fish
LAST DEPLOYED: Thu May 17 09:47:05 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME                          TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
virtuous-fish-inf-chart-demo  ClusterIP  10.233.19.78  <none>       80/TCP   1s

==> v1beta2/Deployment
NAME                          DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
virtuous-fish-inf-chart-demo  1        1        1           0          1s

==> v1/Pod(related)
NAME                                           READY  STATUS             RESTARTS  AGE
virtuous-fish-inf-chart-demo-7db76c4c8d-kxvtj  0/1    ContainerCreating  0         1s


NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=inf-chart-demo,release=virtuous-fish" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```
安装成功,我们将服务通过8088这个端口暴露到host主机，看看是否正常访问。
```
[root@k8s-node1 ~]# export POD_NAME=$(kubectl get pods --namespace default -l "app=inf-chart-demo,release=virtuous-fish" -o jsonpath="{.items[0].metadata.name}")
[root@k8s-node1 ~]# kubectl port-forward $POD_NAME 8088:80
Forwarding from 127.0.0.1:8088 -> 80
Handling connection for 8088
```
> 上面写着8080，但是8080是api-server的端口，所以需要改一下。

重新打开一个shell窗口，发现localhost:8088能正常访问。
```bash
[root@k8s-node1 ~]# curl localhost:8088
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
我们自己的chart已经成功部署到k8s集群，那么要是其他人想要使用这个chart，该怎么办呢？答案是使用私有仓库，前文我们也有提及到。

# 发布Chart
chart 通过测试后可以将其添加到仓库，类似于nexus仓库，我们来搭建一个helm的私有仓库。
**1. 打包chart**
使用`helm package`打包Charts，
```
[root@k8s-node1 ~]# helm package inf-chart-demo/
Successfully packaged chart and saved it to: /root/inf-chart-demo-0.1.0.tgz
```

**2. 搭建私有的helm repo**
任何`HTTP Server`都可以用作 chart 仓库，我们将在`k8s-node1`上搭建仓库。
```
[root@k8s-node1 ~]# docker run --name httpd --restart=always -d -p 33333:80 -v ~/inf-charts/:/usr/local/apache2/htdocs/ httpd
8983ba95c577163c086b0c3aaeba814625ce6d3de4a3c72e7a6685541756203d
```
> 通常httpd等web应用服务器都会有权限设置的问题，这里我们偷个懒直接使用htdocs根目录。

**3. 创建仓库目录**
```
[root@k8s-node1 ~]# mkdir ~/inf-charts
[root@k8s-node1 ~]# mv inf-chart-demo-0.1.0.tgz ~/inf-charts/
```

**4. 索引仓库**
执行`helm repo index`命令，heml会扫描目录下的所有tgz包，并生成index.yaml文件。
```
[root@k8s-node1 ~]# helm repo index ~/inf-charts/ --url http://k8s-node1:33333 # --url是私有仓库的地址
[root@k8s-node1 ~]# tree ~/inf-charts/ -L 2
/root/inf-charts/
├── index.yaml
└── inf-chart-demo-0.1.0.tgz

0 directories, 2 files
```
index.yaml记录的是当前仓库所有的chart信息。
```yaml
[root@k8s-node1 ~]# cat ~/inf-charts/index.yaml 
apiVersion: v1
entries:
  inf-chart-demo:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-05-17T11:00:44.572938568+08:00
    description: A Helm chart for Kubernetes
    digest: 63aaa2ca2b2cbd9036361f19dfef7516cf94d70d4e2fbec0e6ff37708ccb2f98
    name: inf-chart-demo
    urls:
    - http://k8s-node1:33333/inf-chart-demo-0.1.0.tgz
    version: 0.1.0
generated: 2018-05-17T11:00:44.572234877+08:00
```

**5. 使用仓库**
私有的仓库已经搭建好，也上传了我们开发的chart，这时候就可以通知其他人来使用了。
```
[root@k8s-node1 ~]# helm repo add inf-charts http://k8s-node1:33333/
"inf-charts" has been added to your repositories

[root@k8s-node1 ~]# helm repo list
NAME      	URL                                             
stable    	https://kubernetes-charts.storage.googleapis.com
local     	http://127.0.0.1:8879/charts                    
inf-charts	http://k8s-node1:33333/ 
```

**6 更新仓库**
如果repo有更新，执行repo update命令会更新所以已增加的repo
```
[root@k8s-node1 ~]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "inf-charts" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
```

**7. chart使用**
```
[root@k8s-node1 ~]# helm search inf-charts
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                
inf-charts/inf-chart-demo	0.1.0        	1.0        	A Helm chart for Kubernetes
```
chart可以正常被搜索到，那么也可以正常被其他人使用了。

至此，我们已经熟悉了k8s、helm的基本知识以及常用操作，但很多知识还需要多加强化才能够运用自如，接下来我们将会抽空开展网格服务`Service Mesh`的实践。
