### ISSUE TITLE
k8s/基于efk的集群日志管理

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#30]
本次仅介绍在kubernetes 1.9集群下配置EFK（elasticsearch、fluentd、kibana）来集中收集k8s集群日志信息，关于EFK的相关概念在这里不展开描述。

Kubernetes 开发了一个 Elasticsearch 附加组件来实现集群的日志管理，其相关YAML配置可从https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch 获取。若是仅用于学习，可以下载相关配置文件进行实践，但是我们本次实践因为客观原因，我们将按照下面步骤展开实践。
1、抽象elasticsearch
2、配置kibana
3、配置fluentd

# elasticsearch
在我们内网上，已经安装了一个6.2.4的elasticsearch集群，集群本身也安装X-Pack插件。所以本次也是基于版本6.2.4来展开相关实践。需要注意的是，elastic的相关组件从5.0版本后采用统一版本命名，不同版本组合可能会导致不兼容，建议统一。

假设我们es集群信息如下：

| VIP(1) | 账号 | 密码 |
| --- | --- | --- |
| 192.168.64.134 | elastic | 123456 |

这里我们需要将外部的es服务映射成k8s服务。
```
[root@k8s-node1 ~]# mkdir ~/inf-k8s/efk && cd ~/inf-k8s/efk
[root@k8s-node1 efk]# cat << EOF > elasticsearch-svc.yaml
# 创建endpoint
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch-logging
  namespace: kube-system
subsets:
- addresses:
  - ip: "192.168.64.134"  # 这里假设是外部mysql的地址
  ports:
  - port: 9200

# 创建service
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
EOF
```

# kibana
这里我们使用configmap的形式，将kibana.yml的相关参数进行配置。

```
[root@k8s-node1 efk]# cat << EOF > kibana-configmap.yaml
apiVersion: v1
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: http://elasticsearch-logging:9200
    elasticsearch.username: elastic
    elasticsearch.password: "123456" # 跟es集群配置一样
    xpack.monitoring.ui.container.elasticsearch.enabled: true
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kube-system
EOF
```
配置一下Deployment
```
[root@k8s-node1 efk]# cat << EOF > kibana-deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: registry.xxx.com/library/kibana:6.2.4
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        volumeMounts:
        - name: kibana-config
          mountPath: "/usr/share/kibana/config"
          readOnly: true
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config  
          items:
          - key: kibana.yml
            path: kibana.yml
EOF
```
> 一直无法使用系统变量的方式注入配置，也给社区做了反馈https://github.com/elastic/kibana/issues/19435，这里换种思路来实现。

最后，我们来配置kibana Service，
```
[root@k8s-node1 efk]# cat << EOF > kibana-service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging
EOF
```
一切准备就绪，我们来下载kibana的6.2.4版本镜像并上传到我们的私服。
```
[root@k8s-node1 efk]# docker pull docker.elastic.co/kibana/kibana:6.2.4
[root@k8s-node1 efk]# docker tag docker.elastic.co/kibana/kibana:6.2.4  registry.xxx.com/library/kibana:6.2.4
[root@k8s-node1 efk]# docker rmi docker.elastic.co/kibana/kibana:6.2.4
[root@k8s-node1 efk]# docker push registry.xxx.com/library/kibana:6.2.4
```
需要注意的是，elastic的相关镜像在6.0版本以后将迁移到docker.elastic.co做维护，有时可能会很慢，可以打开页面下载后再离线上传到私服。
# fluentd
fluentd改动比较小，我们从官方下载最新的yaml文件
```
[root@k8s-node1 efk]# version=release-1.11
[root@k8s-node1 efk]# url=https://raw.githubusercontent.com/kubernetes/kubernetes/$version/cluster/addons/fluentd-elasticsearch
[root@k8s-node1 efk]# files=(fluentd-es-configmap.yaml fluentd-es-ds.yaml)
[root@k8s-node1 efk]# for file in ${files[*]}; do wget $url/$file; done
```
下载依赖镜像
```
[root@k8s-node1 efk]# docker pull registry.cn-hangzhou.aliyuncs.com/hxpdocker/fluentd-elasticsearch:v2.0.4
[root@k8s-node1 efk]# docker tag registry.cn-hangzhou.aliyuncs.com/hxpdocker/fluentd-elasticsearch:v2.0.4 registry.xxx.com/library/fluentd-elasticsearch:v2.0.4
[root@k8s-node1 efk]# docker rmi registry.cn-hangzhou.aliyuncs.com/hxpdocker/fluentd-elasticsearch:v2.0.4
[root@k8s-node1 efk]# docker push registry.xxx.com/library/fluentd-elasticsearch:v2.0.4
```
修改yaml文件，替换镜像地址
```
[root@k8s-node1 efk]# sed -i 's|k8s.gcr.io|registry.xxx.com/library|g' fluentd-es-ds.yaml
```
找到文件`fluentd-es-configmap.yaml`的` output.conf`节点，增加es的用户账号信息
```
  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      include_tag_key true
      host elasticsearch-logging
      port 9200
      user elastic 
      password 123456
      logstash_format true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
```
其中 user、password为新增项，若是不加会报401错误。

这里需要注意的一点是，fluentd配置了`nodeSelector: beta.kubernetes.io/fluentd-ds-ready: "true"`，我们需要再集群目标主机上手动打上标签，这里我们假设只需收集k8s-node1、k8s-node2主机的日志。
```
[root@k8s-node1 efk]# hosts=(k8s-node1 k8s-node2)
[root@k8s-node1 efk]# for host in ${host[*]}; do kubectl label node $host beta.kubernetes.io/fluentd-ds-ready="true"; done
```

最后我们使用命令`kubectl apply -f ~/inf-k8s/efk`启动所有对象。
```
[root@k8s-node1 efk]# kubectl apply -f ~/inf-k8s/efk
endpoints "elasticsearch-logging" created
service "elasticsearch-logging" created
configmap "fluentd-es-config-v0.1.4" created
serviceaccount "fluentd-es" created
clusterrole "fluentd-es" created
clusterrolebinding "fluentd-es" created
daemonset "fluentd-es-v2.0.4" created
clusterrole "kibana-dashboard-anonymous" created
configmap "kibana-config" created
deployment "kibana-logging" created
service "kibana-logging" created
```
查看服务状态
```
[root@k8s-node1 efk]# kubectl get pod,svc,deployment -n kube-system | grep kibana

po/kibana-logging-7699685f55-568lr         1/1       Running   0          4m
svc/kibana-logging          NodePort    10.233.25.132   <none>        5601:30491/TCP   4m

deploy/kibana-logging         1         1         1            1           4m

[root@k8s-node1 efk]# kubectl get pod,svc,deployment -n kube-system | grep fluentd
po/fluentd-es-v2.0.4-pb465                 1/1       Running   0          6m
po/fluentd-es-v2.0.4-shjpp                 1/1       Running   0          6m

[root@k8s-node1 efk]# kubectl logs -f fluentd-es-v2.0.4-pb465 -n kube-system 
2018-05-25 09:37:28 +0000 [warn]: parameter 'time_format' in <source>
  @id fluentd-containers.log
  @type tail
  path "/var/log/containers/*.log"
  pos_file "/var/log/es-containers.log.pos"
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag "raw.kubernetes.*"
  read_from_head true
  <parse>
    @type "multi_format"
    <pattern>
      format json
      time_key "time"
      time_format "%Y-%m-%dT%H:%M:%S.%NZ"
      time_type string
    </pattern>
    <pattern>
      format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
      time_format "%Y-%m-%dT%H:%M:%S.%N%:z"
      expression "^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$"
      ignorecase false
      multiline false
    </pattern>
  </parse>
</source> is not used.
2018-05-25 09:37:28 +0000 [info]: [elasticsearch] Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http", :user=>"elastic", :password=>"obfuscated"}
2018-05-25 09:37:28 +0000 [info]: [elasticsearch] Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http", :user=>"elastic", :password=>"obfuscated"}
```
我们发现，这里有一个警告，经检测发现，原来我们的docker已经将日志格式化成了json，而不是journald。
```
[root@k8s-node1 efk]# docker info
Containers: 33
 Running: 23
 Paused: 0
 Stopped: 10
Images: 15
Server Version: 17.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
```
登录kibana ui，查看日志是否正常被收集到。
![image](https://user-images.githubusercontent.com/5570216/40538644-d5572b78-6044-11e8-95d2-741462586448.png)

使用上述账密登录，发现日志已正常被收集到es集群里面。
![image](https://user-images.githubusercontent.com/5570216/40538711-00f8f23e-6045-11e8-8ab6-410d1625cb38.png)

![image](https://user-images.githubusercontent.com/5570216/40550556-044f89d4-606d-11e8-9f7b-834d54f1468f.png)

Kubernetes 日志管理系统已经就绪，我们可以根据需要创建不同的 Dashboard，具体方法可参考 Kibana 官方文档。
