### ISSUE TITLE
k8s/配置heapster资源监控

### ISSUE THREAD

**Issue by kaybinwong** [kaybinwong/posts#9]
使用heapster可以更加直观地观察整个集群的健康状态，但kube-spray没有支持，今天我们来看看怎么使用heapster。
# 安装插件
```bash
mkdir addon && cd addon
```
## 安装heapster

**获取最新源码**
```bash
wget https://codeload.github.com/kubernetes/heapster/zip/v1.5.1 && unzip v1.5.1 && rm -rf v1.5.1
```
## 拉取依赖镜像
```bash
images=(
heapster-grafana-amd64:v4.4.3
heapster-amd64:v1.5.1
heapster-influxdb-amd64:v1.3.3
)
for host in ${hosts[*]}; do 
  for image in ${images[*]}; do
    ssh $host "docker pull anjia0532/$image && docker tag anjia0532/$image gcr.io/google_containers/$image && docker rmi anjia0532/$image"
  done
done
```

## 部署heapster
```bash
cd heapster-1.5.1 && kubectl apply -f deploy/kube-config/influxdb/ -f deploy/kube-config/rbac/
```
> 采集监控指标间隔时间是5分钟，所以部署完dashboard要等几分钟才会出现监控信息。

## 访问监控数据
安装完heapster，有两种方式可以访问grafana的dashboard界面。
**k8s api server**
通常我们可以通过dashboard来访问相关k8s服务，我们来获取grafana的访问信息
```
[root@k8s-node1 influxdb]# kubectl cluster-info 
Kubernetes master is running at https://192.168.56.101:6443
Heapster is running at https://192.168.56.101:6443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://192.168.56.101:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
monitoring-grafana is running at https://192.168.56.101:6443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
monitoring-influxdb is running at https://192.168.56.101:6443/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy
```
在访问之前，我们需要做一些简单的授权，如下
```
[root@k8s-node1 heapster-1.5.1]# cat << EOF > heapster-clusterrole-binding.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-dashboard-grafana-anonymous
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["monitoring-grafana"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- nonResourceURLs: ["/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy/*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-grafana-anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-dashboard-grafana-anonymous
subjects:
- kind: User
  name: system:anonymous
EOF
```

执行角色绑定
```
[root@k8s-node1 heapster-1.5.1]# kubectl apply -f heapster-clusterrole-binding.yaml 
clusterrole "kubernetes-dashboard-grafana-anonymous" created
clusterrolebinding "kubernetes-dashboard-grafana-anonymous" created
```

我们来访问`monitoring-grafana`看看。
![image](https://user-images.githubusercontent.com/5570216/40214534-ef2a2b2a-5a8d-11e8-822b-d85dd602300f.png)
**host ip+port**

为了方便访问，我们通过 kubectl edit，或者直接在dashboard将 Service`monitoring-grafana`的类型修改为`NodePort`。
![image](https://user-images.githubusercontent.com/5570216/36068742-67d26118-0f17-11e8-8959-895b21016852.png)

![image](https://user-images.githubusercontent.com/5570216/40163955-ce6b9d72-59ea-11e8-92a5-15487f09d7b7.png)

使用浏览器访问 Grafana 的 Web UI：http://192.168.56.101:31289/， 发现Heapster 已经预先配置好了 Grafana 的 DataSource 和 Dashboard。
![image](https://user-images.githubusercontent.com/5570216/40214471-86ab3c74-5a8d-11e8-9cbc-59ace6d06da3.png)

截至目前，已经了解了k8s的相关概念，集群已经安装完毕，接下来我们将通过实践深入学习 Kubernetes 的各种特性。
